/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/slide_icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFamNavDrawer = 'nav_drawer';
  static const _kFontFamSlide = 'slide_icon';
  static const _kFontPkg = null;

  static const IconData navigation_drawer = IconData(0xe800, fontFamily: _kFontFamNavDrawer, fontPackage: _kFontPkg);
  static const IconData slide_icon = IconData(0xe801, fontFamily: _kFontFamSlide, fontPackage: _kFontPkg);
}
